name: mMarketLib
main: a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.xy.z.spigot.Start
version: 1.0-BETA
description: At this stage, this is a plugin only for the functioning of plugins for 11 and 14 Java
author: "mMarket.top"